Update test maven publishing

diff --git a/.github/workflows/maven-publishing-test.yml b/.github/workflows/maven-publishing-test.yml
--- a/.github/workflows/maven-publishing-test.yml
+++ b/.github/workflows/maven-publishing-test.yml
@@ -1,42 +1,61 @@
-name: Publish project to local or test Maven repository
+name: Publish project to Maven repository
 
 on:
   workflow_call:
+    inputs:
+        group-id:
+          required: false
+          type: string
+        artifact-id:
+          required: false
+          type: string
 
 jobs:
   publish:
     runs-on: ubuntu-latest
+    env:
+      MAVEN_NAME: ${{ secrets.MAVEN_NAME }}
+      MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
+      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
+      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
+      MAVEN_URL: ${{ vars.MAVEN_URL }}
+
     steps:
       - uses: actions/checkout@v2
+
+      # Check if MAVEN_URL is set; if not, fail the job
+      - name: Check if MAVEN_URL is set
+        run: |
+          if [ -z "${MAVEN_URL}" ]; then
+            echo "Error: MAVEN_URL is not set!"
+            exit 1
+          fi
+          
+
+      - name: Grant execute permission for gradlew
+        run: chmod +x gradlew
 
       - name: Set up JDK
         uses: actions/setup-java@v1
         with:
           java-version: 17
 
-      - name: Grant execute permission for gradlew
-        run: chmod +x gradlew
-
       - name: Build project
         run: ./gradlew build
 
-      - name: Publish to test custom Maven repo
-        if: ${{ secrets.MAVEN_NAME != null && secrets.MAVEN_SECRET != null }}
-        run: ./gradlew publish
+      - name: Publish to PuzzleHQsMaven
+        if: ${{ env.MAVEN_NAME && env.MAVEN_SECRET }}
+        run: ./gradlew publishMavenPublicationToPuzzleHQsMavenRepository
         env:
-          MAVEN_NAME: ${{ secrets.MAVEN_NAME }} # token secret (password)
-          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }} # token secret (password)
-          isTest: true
+          MAVEN_NAME: ${{ env.MAVEN_NAME }} # token secret (password)
+          MAVEN_SECRET: ${{ env.MAVEN_SECRET }} # token secret (password)
+          MAVEN_URL: ${{ env.MAVEN_URL }}
+          GITHUB_REF: ${{ github.ref }}
 
-      - name: Publish to Maven local
-        if: ${{ secrets.MAVEN_CENTRAL_USERNAME != null && secrets.MAVEN_CENTRAL_PASSWORD != null }}
-        run: ./gradlew publishToMavenLocal
+      - name: Publish to Maven Central
+        if: ${{ env.MAVEN_CENTRAL_USERNAME && env.MAVEN_CENTRAL_PASSWORD }}
+        run: ./gradlew publishMavenPublicationToMavenLocal
         env:
-          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }} # maven central username
-          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }} #  maven central password
-
-      - name: List all files in local Maven repo under dev.puzzleshq
-        run: |
-          echo "All files under ~/.m2/repository/dev/puzzleshq:"
-          find ~/.m2/repository/dev/puzzleshq -type f || echo "No files found."
-
+          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.MAVEN_CENTRAL_USERNAME }} # maven central username
+          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.MAVEN_CENTRAL_PASSWORD }} #  maven central password
+          GITHUB_REF: ${{ github.ref }}
