add MAVEN_URL to variables

diff --git a/.github/workflows/maven-publishing.yml b/.github/workflows/maven-publishing.yml
--- a/.github/workflows/maven-publishing.yml
+++ b/.github/workflows/maven-publishing.yml
@@ -11,8 +11,17 @@ jobs:
       MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
       MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
       MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
+      MAVEN_URL: ${{ vars.MAVEN_URL }}
+
     steps:
       - uses: actions/checkout@v2
+
+      # Check if MAVEN_URL is set; if not, fail the job
+      - name: Check if MAVEN_URL is set
+        run: |
+          if [ -z "${{ env.MAVEN_URL }}" ]; then
+            echo "Error: MAVEN_URL is not set!"
+            exit 1           
 
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
@@ -31,6 +40,7 @@ jobs:
         env:
           MAVEN_NAME: ${{ env.MAVEN_NAME }} # token secret (password)
           MAVEN_SECRET: ${{ env.MAVEN_SECRET }} # token secret (password)
+          MAVEN_URL: ${{ env.MAVEN_URL }}
           GITHUB_REF: ${{ github.ref }}
 
       - name: Publish to Maven Central
