add GITHUB_REF to env

diff --git a/.github/workflows/maven-publishing.yml b/.github/workflows/maven-publishing.yml
--- a/.github/workflows/maven-publishing.yml
+++ b/.github/workflows/maven-publishing.yml
@@ -11,31 +11,37 @@ jobs:
       MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
       MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
       MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
+      GITHUB_REF: ${{ github.ref }}
     steps:
       - uses: actions/checkout@v2
+
+      - name: Check for gradlew script
+        run: ls -l gradlew || echo "gradlew not found!"
+
+      - name: Grant execute permission for gradlew
+        run: chmod +x gradlew
 
       - name: Set up JDK
         uses: actions/setup-java@v1
         with:
           java-version: 17
 
-      - name: Grant execute permission for gradlew
-        run: chmod +x gradlew
-
       - name: Build project
         run: ./gradlew build
 
       - name: Publish to custom Maven repo
-        if: ${{ env.MAVEN_NAME != '' && env.MAVEN_SECRET != '' }}
+        if: ${{ env.MAVEN_NAME && env.MAVEN_SECRET }}
         run: ./gradlew publish
         env:
           MAVEN_NAME: ${{ env.MAVEN_NAME }} # token secret (password)
           MAVEN_SECRET: ${{ env.MAVEN_SECRET }} # token secret (password)
+          GITHUB_REF: ${{ github.ref }}
 
       - name: Publish to Maven Central
-        if: ${{ env.MAVEN_CENTRAL_USERNAME != '' && env.MAVEN_CENTRAL_PASSWORD != '' }}
+        if: ${{ env.MAVEN_CENTRAL_USERNAME && env.MAVEN_CENTRAL_PASSWORD }}
         run: ./gradlew publishToMavenCentral
         env:
           ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.MAVEN_CENTRAL_USERNAME }} # maven central username
           ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.MAVEN_CENTRAL_PASSWORD }} #  maven central password
+          GITHUB_REF: ${{ github.ref }}
 
